version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - nodejs
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  nodejs:
    build: .
    ports:
      - "3000:3000"
